FROM debian
ADD docker.list /etc/apt/sources.list.d/
RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p jusmi.com/img && \
    chmod -R 754 /var/www/jusmi.com/ && \
    useradd Ju && groupadd Smi && usermod -aG Smi Ju && \
    chown -R Ju:Smi /var/www/jusmi.com/ && \
    sed -i 's/\/var\/www\/html/\/var\/www\/jusmi.com/g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Ju/g' /etc/nginx/nginx.conf
ADD index.html /var/www/jusmi.com/
ADD img.jpg /var/www/jusmi.com/img/
CMD ["nginx", "-g", "daemon off;"]
